### ISSUE TITLE
Check br_family field for some value is killing lot of results with NULL value

### ISSUE THREAD

**Issue by sphinks** [fishtown-analytics/snowplow#34]
I have faced an issue with `br_family` NULL value in Redsfhit. There is a condition in `snowplow_page_views.sql` at line 307 `where a.br_family != 'Robot/Spider'`. In case there is a NULL value in `br_family`, such condition will not output that rows, cause NULL can not be equal or not equal to anything. As result, lot of pageviews with null value in br_family are totaly lost in result tables of DBT model.

**Comment by drewbanin** [comment]
Thanks for the report @sphinks! This should be a pretty quick fix, and I don't think there's any harm in allowing null values in `br_family`. Good catch!

**Comment by sphinks** [comment]
Have resolved it temporary with workaround in DBT project settings:
```
snowplow:
    pre-hook: "update atomic.events set br_family = '' where br_family ISNULL"
```

**Comment by drewbanin** [comment]
Hey @sphinks! I try to avoid mutating "source" data, and would instead recommend doing this with a base model!

You could make a dbt model like:
```
-- models/snowplow/base/snowplow_base_events_fixed.sql

select
  *,
  nullif(br_family, '') as br_family
from atomic.events
```

Unfortunately, you can't actually use the `*`, and would instead need to enumerate the column names. That might be a good opportunity to use the [star macro](https://github.com/fishtown-analytics/dbt-utils#star-source). 

Once you have the base model, you can pass it into the Snowplow package with:

```
# dbt_project.yml

models:
  snowplow:
    vars:
      'snowplow:events': "{{ ref('snowplow_base_events_fixed') }}"
```

Thanks for the ping on this issue -- it fell off of my todo list! Will try to make a PR asap!

**Comment by drewbanin** [comment]
Thanks @sphinks :)

Just merged the PR and cut a new release: https://github.com/fishtown-analytics/snowplow/releases/tag/0.5.2 🎉

**Comment by sphinks** [comment]
@drewbanin great! Thanks!
