### ISSUE TITLE
Fails to exclude page views from pingdom

### ISSUE THREAD

**Issue by Selvaticus** [fishtown-analytics/snowplow#74]
I have encountered the case where page hits from pindgom are not behind excluded.

In this particular case the **useragent** from pindgom comes like this: 
`
Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PingdomTMS/0.8.5 Safari/534.34`

The regex is only setup to pick up `pingdom` and `PingdomBot`

**Comment by jtcohen6** [comment]
I believe this was resolved in #75, and it has a more general solution (across all adapter implementations) in #81
